name: ML_Gweh
description: "Handwritten recognition for kids"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  change_app_package_name: ^1.5.0
  cupertino_icons: ^1.0.8
  firebase_app_check: ^0.3.2+4
  firebase_core: ^3.12.0
  firebase_storage: ^12.4.3
  flutter:
    sdk: flutter
  flutter_drawing_board: ^0.9.5
  flutter_launcher_icons: ^0.14.3
  flutter_sound: ^9.28.0
  flutter_svg: ^2.0.17
  image: ^4.5.3
  lottie: ^3.3.1
  path_provider: ^2.1.5
  permission_handler: ^11.4.0
  tflite_flutter: ^0.11.0
  video_player: ^2.9.3
  audioplayers: ^6.3.0
  shared_preferences: ^2.5.2
  wakelock_plus: ^1.2.10

dev_dependencies:

  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:

    - assets/
    - assets/voice_recognition.tflite
    - assets/models/
    - assets/menulis/
    - assets/menulis/
    - assets/menulis/alfabet/
    - assets/menulis/hijaiyah/
    - assets/menulis/angka/
    - assets/menulis/alfabet/huruf/
    - assets/menulis/hijaiyah/huruf/
    - assets/menulis/angka/folder_angka/
    - assets/home/
    - assets/menu/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
  adaptive_icon_background: "#ffffff"  # Untuk ikon adaptive Android
  adaptive_icon_foreground: "assets/app_icon.png"
