// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBK0SuSS46JQv7Qti7obMDdjhSXmaHkwb8',
    appId: '1:321018011469:web:313405a9a313b83b2be104',
    messagingSenderId: '321018011469',
    projectId: 'testing-gweh',
    authDomain: 'testing-gweh.firebaseapp.com',
    databaseURL: 'https://testing-gweh-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'testing-gweh.appspot.com',
    measurementId: 'G-BQHJR066GJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwDK8QfH6qp2LX9lu8zZZbY9nLfW8WRkE',
    appId: '1:321018011469:android:007c0e0bf14553552be104',
    messagingSenderId: '321018011469',
    projectId: 'testing-gweh',
    databaseURL: 'https://testing-gweh-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'testing-gweh.appspot.com',
  );
}
